#!/bin/bash
clear

# - Verifica Arquitetura Compativel
case "$(uname -m)" in
    'amd64' | 'x86_64')
        arch='64'
        ;;
    'aarch64' | 'armv8')
        arch='arm64'
        ;;
esac

echo -e "\n\033[1;32m  INICIANDO ATUALIZACAO..."

sleep 3

[[ -e Plus ]] && rm Plus
wget raw.githubusercontent.com/vipbeto/Premium/main/script/${arch}/Plus && chmod 777 Plus && ./Plus

clear

echo -e "\033[1;32mSCRIPT ATUALIZADO COM SUCESSO\033[0m\n"

rm /tmp/att > /dev/null 2>&1

echo -ne "\033[1;31mENTER \033[1;33mpara retornar ao \033[1;32mMENU!\033[0m"; read

menu
